[package]
name = "runner"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
cli = { path = "../cli" }
base = { path = "../base" }
sled = "0.34.7"
toml = "1.1.4"
serde = { version = "1.0.229", features = ["derive"] }
